- hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  
  tasks:
    - name: Install Minimal Graphic Interface and dig Command
      apt: 
        state: present
        update_cache: yes
        name:
          - "xfce4"
          - "dnsutils"
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Show Docker Version
      command: "docker --version"
      register: output

    - debug: msg="{{ output.stdout }}"
    - name: Add remote "ubuntu" user to "docker" group
      remote_user: ubuntu
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker
    - name: Install docker-compose
      remote_user: ubuntu
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Install Chromium
      apt: 
        name:
          - "chromium-browser"

    - name: Show Chromium Version
      command: "chromium-browser --product-version"
      register: output 
    
    - debug: msg="Chromium version {{ output.stdout }}"

    - name: Git pull from repo
      git: 
        repo:  git@github.com:F8aAr/InfluxDB-Grafana-docker-compose.git
        dest: /home/git-repo
        accept_hostkey: true
        key_file: /root/.ssh/personal_git
        version: master

    - name: Run Script
      command: "bash /home/playbooks/script.sh"
      register: output
    - debug: msg="{{ output.stdout }}"